const Brands = [
    // A
    "Alpha",
    "Autodromo",
    "Apple",
    "Accutron",
    "Air Blue",
    "Alpina",
    "Aragon",
    "Armitron",
    "Audemars Pigue",
    "Aquanero",
    "Armand Basi",
    "A.Lange & Sohne",
    "Ancon",
    "Aquadive",

    // B
    "Ball",
    "Borealis",
    "Benarus",
    "Blacklist",
    "Balticus",
    "Baume et Mercier",
    "Blancpain",
    "Breitling",
    "Bremont",
    "Bulgari",
    "Bulova",
    "Blenheim",
    "Bell & Ross",
    "Bali'Hai",

    // C
    "Cartier",
    "Casio",
    "Chanel",
    "Citizen Watch Co.",
    "Calvin Klein",
    "Concord",
    "Corum",
    "Croton",
    "Chronologia",
    "Chopard",

    // D
    "D1 Milano",
    "Dolce & Gabbana",
    "Damasko",
    "Doxa",
    "Detomaso",
    "Davosa",
    "Roger Dubuis",
    "Deep Blue",
    "Dufa",

    // E
    "Ebel",
    "Egard",
    "Edox",
    "Elgin",
    "Emporio Armani",

    // F
    "Frédérique Constant",
    "Fossil",
    "Fitbit",
    "Fendi",
    "Fortis",
    "Fortuna",
    "Firebird",
    "Fresh",

    // G
    "Garmin",
    "Glashütte Original",
    "Glycine",
    "Gruen Watch Co",
    "Gruppo Gamma",
    "G-Shock",
    "Guess Watches Co.",
    "Grand Seiko",
    "Gucci",
    "Ginault",
    "Gevril",
    "Guess",

    // H
    "Hamilton",
    "Harding",
    "Haldor",
    "Hanowa",
    "Helson",
    "Heritor",
    "Hermès",
    "Hublot",
    "Hew & Luey",
    "H20",
    "Heroic",

    // I
    "International Watch Company",
    "Invicta",
    "Invicta (LOL)",
    "Isobrite",

    // J
    "Jaeger-LeCoultre",
    "Jacob & Co.",
    "Jean Perret",
    "Junghans",
    "Jorg Gray",
    "JBW",

    // k
    "Kenneth Cole",

    // L
    "Laco",
    "Lancashire",
    "Lew & Huey",
    "Longines",
    "Luminox",
    "Lorus",

    // M
    "Marc & Sons",
    "Mathey-Tissot",
    "Maurice Lacroix",,
    "Marathon",
    "Makara",
    "Meccaniche Veneziane",
    "MB&F",
    "MeisterSinger",
    "Melbourne",
    "mb-microtec",
    "Mido",
    "Montblanc",
    "Moschino",
    "Mossimo",
    "Movado",
    "MVMT",
    "MMM",
    "MOS",
    "Mon Dragon",
    "Franck Muller",

    // N
    "Newgate",
    "Nixon",
    "Nethuns",
    "Nomos Glashütte",
    "NFW",
    "Nike",

    // O
    "Omega",
    "Ocean Crawler",
    "Orient",
    "Ollech & Wajs",
    "Oris",
    "Out Of Order",
    "OceanX",
    "Orion",
    "Original Grain",

    // P
    "Panerai",
    "Parmigiani Fleurier",
    "Parnis",
    "Prada",
    "Antoni Patek",
    "Patek Philippe & Co.",
    "Perrelet",
    "Pequignet",
    "Petrodvorets",
    "Philip Zepter",
    "Piaget",
    "Prometheus",
    "Adrien Philippe",
    "Henry Pitkin",
    "Pobeda",
    "Phoibos",
    "Poljot",
    "Prada",
    "Pulsar",
    "P.K. Horology",

    // R
    "Raven",
    "Ralf Tech",
    "Ralph Lauren",
    "Rado",
    "Raymond Weil",
    "Raketa",
    "Renato",
    "Ракета",
    "David Ramsay",
    "Razer Inc.",
    "Regina",
    "Regia",
    "Reguladora",
    "Ressence",
    "Reign",
    "Revue Thommen",
    "Richard Mille",
    "Roamer",
    "Rodania",
    "Rolex",
    "Ronda AG",
    "Rotary",
    "Daniel Roth",

    // S
    "Samsung",
    "Sandoz",
    "Schwarz Etienne",
    "Sector",
    "Seiko",
    "Seikosha",
    "Sekonda",
    "Shinola Detroit",
    "Sinn",
    "SSIH",
    "Skagen",
    "Alexander Shorokhoff",
    "Slava",
    "Roger W. Smith",
    "SMH",
    "Solvil et Titus",
    "Speake-Marin",
    "Sprout",
    "Spinnaker",
    "Steinhart",
    "Stowa",
    "Stuhrling",
    "Simplify",
    "Squale",
    "Swatch Group",
    "Strumento Marino",
    "Strider",
    "Studer Schild",
    "Straton",
    "Stuckx",


    // T
    "Tag Heuer",
    "Tag",
    "Terra Cielo Mare",
    "Technos",
    "Seth Thomas",
    "Thomas Tompion",
    "Tevise",
    "Tisell",
    "Tiffany & Co.",
    "Timex",
    "Tellus",
    "Tommy Hilfiger",
    "Tourneau",
    "ToyWatch",
    "Traser",
    "Tudor",
    "TW Steel",
    "Titoni",
    "TimeForce",
    "Tsovet",
    "Tsao",
    "Tschuy-Vogt",
    'Trump',


    // U
    "Ulysse Nardin",
    "Universal Genève",
    "U-Boat",


    // V 
    "Vacheron Constantin",
    "Vacuum Chronometer Corporation",
    "Valjoux",
    "Versus",
    "Ventus",
    "Versus (Versace)",
    "Versace",
    "Victorinox",
    "Visconti",
    "Visitor",
    "Virata",
    "Vostok",


    // W
    "Waltham International",
    "Waltham",
    "Christopher Ward",
    "Wenger",
    "Westclox",
    "West End",
    "Joseph Windmills",
    "Harry Winston",
    "Werenbach",
    
    // X

    // Y

    // Z
    "Zelos",
    "Zodiac",
    "Zixen",

    // #123
    "38°"

]

export default Brands